version: '3.8'

services:
  gitlab-ee:
    container_name: "gitlab-ee"
    image: "gitlab/gitlab-ee:rc"
    restart: "always"
    networks:
      - "group4_net"
    ports:
      - "4043:443"
      - "4080:80"
      - "4022:22"
    volumes:
      - "/home/ubuntu/gitlab-docker-server/config:/etc/gitlab"
      - "/home/ubuntu/gitlab-docker-server/logs:/var/log/gitlab"
      - "/home/ubuntu/gitlab-docker-server/data:/var/opt/gitlab"
    hostname: "gitlab.en.605.609.81.sp24.group4.com"
    shm_size: "256m"
    environment:
      - GITLAB_OMNIBUS_CONFIG="external_url 'http://gitlab.605.609.81.sp24.group4.com'"

  sonarqube:
    container_name: "sonarqube"
    image: "sonarqube:latest"
    restart: "always"
    networks:
      - "group4_net"
    ports:
      - "9000:9000"
    environment:
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
    volumes:
      - "/home/ubuntu/sonarqube/data:/opt/sonarqube/data"
      - "/home/ubuntu/sonarqube/extensions:/opt/sonarqube/extensions"
      - "/home/ubuntu/sonarqube/logs:/opt/sonarqube/logs"

  db:
    container_name: "sonar-db"
    image: "postgres:12-alpine"
    restart: "always"
    networks:
      - "group4_net"
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonar
    volumes:
      - "/home/ubuntu/sonarqube_db/data:/var/lib/postgresql/data"

  gitlab-runner:
    container_name: "gitlab-runner"
    image: "gitlab/gitlab-runner:latest"
    restart: "always"
    depends_on:
      - "gitlab-ee"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/home/ubuntu/gitlab-runner/config:/etc/gitlab-runner"
      - "/home/ubuntu/gitlab-runner/data:/home/gitlab-runner"
    networks:
      - "group4_net"

networks:
  group4_net:
